CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_ADC=y
CONFIG_SERIAL=y
CONFIG_UART_ESP32=y

CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_BUILD_OUTPUT_BIN=y



# Enable stack monitoring and the shell/log output
CONFIG_INIT_STACKS=y
CONFIG_STACK_USAGE=y
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_AUTO=n
# CONFIG_SYS_HEAP_RUNTIME_STATS=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL_MS=5000

# Increase the main stack size (Crucial for Wasmtime/Pulley)
CONFIG_MAIN_STACK_SIZE=53000
# CONFIG_MAIN_STACK_SIZE=63000
# CONFIG_MAIN_STACK_SIZE=95000
# CONFIG_ISR_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=16384
# CONFIG_MAIN_STACK_SIZE=32768

# Since you are using Zephyr's allocator for Rust, 
# make sure the heap is also large enough to hold Wasm modules
CONFIG_HEAP_MEM_POOL_SIZE=307200
# CONFIG_HEAP_MEM_POOL_SIZE=262144
# CONFIG_HEAP_MEM_POOL_SIZE=253000
CONFIG_ADC_LOG_LEVEL_DBG=n

CONFIG_NEWLIB_LIBC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0

CONFIG_STACK_SENTINEL=n
CONFIG_HW_STACK_PROTECTION=n
CONFIG_BOOT_BANNER=n

#CONFIG_RUST=y

# If you need heap allocation from Rust:
#CONFIG_RUST_ALLOC=y

# CONFIG_RISCV_ISA_EXT_A=y
# CONFIG_RISCV_ISA_EXT_M=y
# CONFIG_RISCV_ISA_EXT_C=y

